#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;


namespace Samples
{
    public class HomeController_Generated
    {
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task Get(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var context = httpContext;
            await controller.Get(context);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task Blah(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var result = controller.Blah();
            await new Microsoft.AspNetCore.Mvc.ObjectResult(result).ExecuteResultAsync(controller.ControllerContext);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task Status(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var statusValue = httpContext.Request.RouteValues["status"]?.ToString();
            System.Int32 status = default;
            if (statusValue == null || !System.Int32.TryParse(statusValue, out status))
            {
                status = default;
            }
            var result = controller.Status(status);
            await result.ExecuteResultAsync(controller.ControllerContext);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task SlowTaskStatusCode(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var result = await controller.SlowTaskStatusCode();
            await result.ExecuteResultAsync(controller.ControllerContext);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task FastValueTaskStatusCode(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var loggerFactory = httpContext.RequestServices.GetRequiredService<Microsoft.Extensions.Logging.ILoggerFactory>();
            var result = await controller.FastValueTaskStatusCode(loggerFactory);
            await result.ExecuteResultAsync(controller.ControllerContext);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task DoAsync(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var context = httpContext;
            var q = httpContext.Request.Query["q"].ToString();
            await controller.DoAsync(context, q);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task HelloDavid(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var result = controller.HelloDavid();
            await new Microsoft.AspNetCore.Mvc.ObjectResult(result).ExecuteResultAsync(controller.ControllerContext);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task GetAsync(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var name = httpContext.Request.RouteValues["name"]?.ToString();
            var result = await controller.GetAsync(name);
            await new Microsoft.AspNetCore.Mvc.ObjectResult(result).ExecuteResultAsync(controller.ControllerContext);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task Hello(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var formCollection = await httpContext.Request.ReadFormAsync();
            var s = formCollection["s"].ToString();
            var id = httpContext.Request.Headers["id"].ToString();
            var pageValue = httpContext.Request.Query["page"].ToString();
            System.Nullable<System.Int32> page = default;
            if (pageValue != null && System.Int32.TryParse(pageValue, out var pageTemp))
            {
                page = pageTemp;
            }
            var pageSizeValue = httpContext.Request.Query["pageSize"].ToString();
            System.Nullable<System.Int32> pageSize = default;
            if (pageSizeValue != null && System.Int32.TryParse(pageSizeValue, out var pageSizeTemp))
            {
                pageSize = pageSizeTemp;
            }
            var result = controller.Hello(s, id, page, pageSize);
            await new Microsoft.AspNetCore.Mvc.ObjectResult(result).ExecuteResultAsync(controller.ControllerContext);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task Post(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var obj = await System.Text.Json.JsonSerializer.DeserializeAsync<System.Text.Json.JsonElement>(httpContext.Request.Body);
            var result = controller.Post(obj);
            await result.ExecuteResultAsync(controller.ControllerContext);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task PostAForm(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            var form = await httpContext.Request.ReadFormAsync();
            controller.PostAForm(form);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute]
        public async System.Threading.Tasks.Task Authed(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var controller = new Samples.HomeController();
            controller.Authed();
        }
        
        public void MapRoutes(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder routes)
        {
            routes.Map("/", Get).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/blah", Blah).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/status/{status}", Status).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/slow/status/{status}", SlowTaskStatusCode).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/fast/status/{status}", FastValueTaskStatusCode).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/lag", DoAsync).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/hey/david", HelloDavid).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/hey/{name?}", GetAsync).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/hello", Hello).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute());
            routes.Map("/", Post).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpPostAttribute());
            routes.Map("/post-form", PostAForm).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpPostAttribute());
            routes.Map("/auth", Authed).WithMetadata(new Microsoft.AspNetCore.Mvc.HttpGetAttribute(), new Microsoft.AspNetCore.Authorization.AuthorizeAttribute());
        }
    }
}
